In [3]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)


In [1]:
import numpy as np

In [24]:
random_array = np.random.randint(low=1, high=100, size=(6, 4))

print(random_array)

[[68 34 64 30]
 [88 79 31 38]
 [91 36 42 16]
 [35 71 89 67]
 [30 28 60 52]
 [23  8 47 17]]


In [28]:
random_array[0:3:2]
row5=sum(random_array[0:3:2])
random_array[1:5:2]
row6=sum(random_array[1:5:2])
random_array[4]=row5
random_array[5]=row6
print(random_array)

[[ 68  34  64  30]
 [ 88  79  31  38]
 [ 91  36  42  16]
 [ 35  71  89  67]
 [159  70 106  46]
 [123 150 120 105]]
